language: d
sudo: false

install: ./install-deps.sh
script: ./run-test.sh

env:
    secure: "sRHFb5QTRsK+1NBnS5ljyM02qgxXhalMh9xCffg+mRDuUWDD81wrQg68tagFEwQIGB+cjsha7Ywzng9+C3QZWEfBPX6G7UpQcI+B8itnoYvun2Nd+H/EYp3sUjJzufzSBaZX0oLjGgoPQbkZLbLp6WHKAp2JugK6xk6CkxXLJZwNkNJ7nBu/hnTFKShZY3EBnXUzB5CLj2qCp+L94A8mgKedrjkEnfUrVG967W101SWZve1fWmQ/ry2lpyLTTly9I7phHvl72mupT5nkEC2zfqf1YceJSW9EA7Ocoa8uQyp3RnpsdnOMxFIBbpcdXbEvkadHw2PyABF79p6fT/GngAp/voPabXqFiwjM0BMjqeZO9+FJgATBUdXuSOOkm7npdSvHtlMNUGFTFpgVlep7tddakUrL9o5V/iQHc6FYy6Tvw6EYa18M4l0R/20c9Nik8KoGknDS3hOxzEL2cx1vYIPRWVrHHRShfwsnACibmDxhq0MFhmVgAv0elnAXOBGD6xK3p46Lkw2THLuPpU5sotCVeCxdpUliMOyTkqCBK9O4sTIoSfsQfPcD6TrjfpPjKVn8ElwoCv+pfxQOO0roF1M5u3GYrBnQTmk7JGkxXidqnw8jPdZ2jUGSTtNYXveMjNT+vrbzH8/V6Fg1D38Wd2k4sEosc2W/xMXAsuQuUE0="

matrix:
    include:
        - d: dmd
        - d: dmd-2.067.1
        - d: ldc
        - d: ldc-0.15.1
        - d: gdc
        - d: gdc-5.2.0
        - d: gdc-4.9.0
