language: d
sudo: false

env:
    secure: "fIlz/7daOJGdXTbrBGaqiaiZFcKkKUSS6CIJ6FT0eZmBSaisfTyUGRWfOMPdejj5RVVayGR+AuxEPZ2DJbgooDGjUOeYWGgJZkvr2AJmFU+15ZvAO9g/YqUVY3+RQCD5c2uM8MXbDohqn7PbyFH8JeUz9dlHo7JXwQxr7ILHXfIdat7GA5Lli+QiWD0bjdwufhySZORP7v+x8wlXFxcD9LyyKQbBs3PS6U3DTX9TNXc+JdczLoOz8M9T+zjsfJv2gPaW/tUm004a7cKEZvrIw3VRYsTOUMthTuZgZM9+D2jLxP5j92BShuAKxlFoLALYkL8qLCeQUOrxsrl7ll6gMnq60JmVTE2gqeVNA35V//nQs9nsKY2HkyEy066HPj2H4w9481n8JWU3PZ5PGHaMARmE3SE78edIFOFBdTmMwjOVUULc7hr7SgxPtGOfyoP730myzaKTCF46o4XB55+rYfB/558n6Es8uKrA9MKDWHkTnITTd+hlDJVseGtVZvn6+Si76yd56rfcWJZ7unrJyOmJDp67ceH/G+DDDz2oKXo1GScqkXImirPoNqOHXNp7hSl0nNJ1giXxVS7ZAV6QBKZu9GBJm61cJev7QpEeV76ZczyxgDb/YreWlYTNSQxBpLtiuTdMIt9TakYeSFfPoVXqNH97qUfGqzTVGz9RtrM="
    secure: "GCJ6ZGHT4gOHGhIypiPEyEvVvhOSPnfErqfZfGOiF7POgfQfCMEZHPrsl0Fl4jW0PoIOf8rNIqmi1EVC6IfE4HX9Iuzx37Or9tTkSLn376eRRFojAHwD2L1GH1t1Xgk20DFttQ11MEVvMmvf70Qz66rCP6HLuFY3WxdilZOkx6SPVT+jxOu1pNIkrKRIPQev5Ij/EWMbLgiwSNbmlflwBKBufvyha4wkjh7dkn1rlcbBPhmpTe2/KcjB3Yac6KZ/xbXvQEwqc6MBUP322oR3rad1bir6qam+wY2in0QFh0/9clamsGkO/oaGbUDOMBt0XUA3oqpBEqfKEPV8nOkCjjdsqxRysHdwTaL+oFPkehDIAT/NsWRjpZgoAPp140/na7BtdGaw5mb9ih7tUiH0UtAe/Y+WfmQIBzsHs1xt9PKb+YSEwDxC6Q8r9U44vjlxAL+AxQbmeXbig7idHFfkCEKY22oFB/L4/xj47SQaeN6kLcXrjJIDE3yEMN7oScebgfFxV+YrI8XqzPq0KnKBjuUW8qNOCTLT8j4sP4kigb00AlxhTdmk90H08BGVyGQcWBOhUXy0ikqOpvhBNjbnBdFtCDtmppKXWpTHvNXFf5lB2STnZwjWCIp8E++k9ff7IVzLlxLWi1CGlmR98v6zcGmlJ2wlJXRj31FdoulubiM="

matrix:
    include:
        - d: dmd
        - d: ldc
        - d: gdc
